version: '3'
networks:
  nginx-php-mysql:

services:
  web:
    build:
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php-service
      - mysql-service
    networks:
      - nginx-php-mysql
  php-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    ports:
      - "9000:9000"
    networks:
      - nginx-php-mysql
  mysql-service:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0375Ihor_
      MYSQL_ROOT_HOST: localhost
      MYSQL_PASSWORD: Devbase75_ #Ihorbase75_
      MYSQL_USER: dev #ihor
      MYSQL_DATABASE: notes
    volumes:
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "33306:3306"
    restart: always
    networks:
      - nginx-php-mysql

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/var/www/project
    working_dir: /var/www/project